### ISSUE TITLE
Issue with TinyMCE integration — adds unexpected shortcodes

### ISSUE THREAD

**Issue by selfagency** [Ranks/emojione#132] opened 2015-09-29 17:16 UTC
Hi,

I'm trying to enable emojione's unicode > shortcode function within TinyMCE, so that it triggers on the save of forms that contain TinyMCE windows on textareas.

This is the JS I'm using, based on [TinyMCE's API](http://www.tinymce.com/wiki.php/api4:event.tinymce.Editor.SaveContent):

```javascript
    return tinyMCE.init({
    setup: function(editor) {
        editor.on('SaveContent', function(e) {
          var input = e.content;
          var output = emojione.toShort(input);
          e.content = output;
      });
```
`e.content` in this case is the contents of the TinyMCE window. 

It appears to work — it's converting unicode emoji characters to shortcodes — except for some reason it's adding `:hash:` shortcodes at the beginning of each paragraph and throughout the content.

Any idea why that might be the case?

**Comment by mikebe11** [comment] 2015-09-29 18:38
Hmm, that's pretty odd. There are only two code points that should be converted to `:hash:`, 0023-fe0f-20e3 and 0023-20e3. Is the character encoding for your page utf-8? How's the input and output look in the console? Is it filtered anywhere before reaching that function?

I don't know the ins and out of TinyMCE. Their site doc mentions a **format** property (*Format of the contents normally "html"*). Could that be affecting things?

**Comment by mikebe11** [comment] 2015-10-14 23:45
@selfagency Have you found a solution for this or any new details that might be helpful?

**Comment by selfagency** [comment] 2015-10-14 23:58
Sadly, no. Have you tried tinkering with a TinyMCE integration at all to see if you can replicate my problem?

**Comment by mikebe11** [comment] 2015-10-15 00:14
No, I haven't. So much to do lately I haven't had time. I'd like to try to it tonight. I'll see how the TinyMCE setup goes. Hopefully it's quick. I've never worked with it.
Can you provide a sample of some input that's getting all the extra shortnames or is it any and all input?
Do you have anything I can use to get started? How about a fiddle to check out?
http://fiddle.tinymce.com/

**Comment by mikebe11** [comment] 2015-10-15 03:32
I put together a basic tinyMCE setup. Things are working ok. I'm not getting the results you described. If you have some text that's coming out wrong for you please send it over for me to test with.

**Comment by selfagency** [comment] 2015-10-15 14:55
The only issue I have had, as I mentioned, is if I paste in an emoji character, in addition to converting it to a text shortcode, it adds superfluous :hash: shortcodes all throughout my content on save. Did you try using the same filter as I have above?

**Comment by mikebe11** [comment] 2015-10-16 04:20
Yes, tried your snippet and also tried with the submit event. Results were as expected.
```javascript
editor.on('submit', function(e) {
    e.preventDefault();
    var input = this.getContent();
    console.log(input);
    var output = emojione.toShort(input);
    console.log(output);
});

editor.on('SaveContent', function(e) {
    debugger;
    var input = e.content;
    var output = emojione.toShort(input);
    e.content = output;
});
```
Unfortunately, I can't replicate your issue.

**Comment by mikebe11** [comment] 2015-12-22 19:48
@selfagency Checking in. Any progress on getting TinyMCE to work for you? Besides the addition of the new emoji there have been some other updates to the js library file. If it's still not working for you, have you tried the latest release?

**Comment by mikebe11** [comment] 2016-02-09 22:30
@selfagency We were unable to reproduce your error plus this issue has been in-active for over a month so I'm going to close it. If you have more code that will for certain recreate the error feel free to reopen this with that code.

**Closed by mikebe11** 2016-02-09 22:30 UTC
Labels: help wanted
