### ISSUE TITLE
Add support for Emoji 4.0 standard

### ISSUE THREAD

**Issue by Naudiz** [Ranks/emojione#382] opened 2016-10-21 14:37 UTC
Emoji 4.0 includes (among others) support for gendered emojis and professions.
[http://blog.emojipedia.org/whats-planned-for-emoji-4-0/](url)

Google has fully implemented Unicode 4.0 in Android 7.1 dev-preview.
Twitter's twemoji is also up-to-date already.

EmojiOne should follow and also update those emojis.

**Comment by Peque** [comment] 2016-10-23 14:04
Duplicate of #358?

**Comment by milesj** [comment] 2016-12-06 06:15
Would like this as well.

**Comment by bcharbonnier** [comment] 2017-02-10 08:31
Seems like EmojiOne is last one that did not implement this Emoji 4.0 standard 😞 
Apple 🆗  Twemoji 🆗  Google 🆗 

It's kind of sad.. I remember days where EmojiOne was the first one to implement changes as soon as they were available.

Nonetheless, keep up the good work, new look in v3.0 sounds amazing !!

**Comment by caseyahenson** [comment] 2017-04-20 19:55
The release of 3.0 includes full support for Emoji 4.0. Our 3.0 release brought about many changes to our assets, licensing structure, repo, websites, etc which unfortunately did delay our typical release cycle. We plan to be much more expedient in releasing updates going forward.

**Closed by caseyahenson** 2017-04-20 19:55 UTC
