### ISSUE TITLE
Is this project available as a font?

### ISSUE THREAD

**Issue by pauldhunt** [Ranks/emojione#105] opened 2015-05-29 21:23 UTC
Perhaps the answer is buried somewhere, but have these resources been compiled into an actual font? the OpenType format has recently added support for SVG artwork and thus it is conceivable that all of the artwork could be compiled into a font format. Has this been considered? Would this be desirable to anyone?

**Comment by emitstop** [comment] 2015-05-29 21:54
Hey Paul,

We love to see that svg in opentype has made more progress since we started this project, however from what we can tell, Firefox 26+ is the only browser currently supporting multicolor svg in opentype. With the rest reduced the svgs to a single color. Unfortunately, the vast majority of our emoji would not be recognizable when flattened like that. I believe all of our emoji would need to be modified and optimized for this. Once support is there, I do think svg in opentype will be the ideal emoji solution.

If anyone wants to to go ahead and create the font, you're absolutely welcome to and we hope you'll submit a pull request. However, it's not currently something we've currently got on our development roadmap.

**Comment by pauldhunt** [comment] 2015-05-29 22:22
Awesome thanks for the thoughtful response. One thing with the SVG in OpenType is that it IS on the bleeding edge of technology and currently in a chicken-and-egg scenario where not many developers want to sink much time into developing a font that does not yet have wide support, but that support will not come until there are popular fonts that require it. This was the case with the Apple Color Emoji font that came on the scene as the first, non-proprietary application of emoji: all the sudden .notdef boxes started showing up everywhere in media and platforms that were not ready to support them (hence your solution here).

My team here at Adobe is trying to drive awareness for the new format and hopefully hasten its adoption. I’ll talk to them to see if there is interest in taking the great work you have done thus far and compiling it into a font. Will keep you posted.

**Comment by thinkrick** [comment] 2015-05-29 22:33
Hi Paul,

Pleasure to hear you from directly.  We'd embrace any help or partnership with Adobe to convert our emoji set to an opentype.  I don't know the process involved and if b&w fallback is required.  Emoji One is a fun non-profit for us and our resources are limited.

BTW, we also have a major update to our art coming in a few weeks including unicode 7.0 graphics and of course a well designed middle finger!  :)

Hope to hear from you soon.
Rick Moby, Founder

**Comment by wp9015362** [comment] 2015-05-29 22:47
This issue is a duplicate of:

https://github.com/Ranks/emojione/issues/26

Regards

**Comment by wp9015362** [comment] 2015-09-11 06:54
Looks like Google wants to create a font for Emoji One, see:

https://github.com/googlei18n/noto-emoji/issues/9

:open_mouth: :smiley: 

Regards

**Comment by miguelsousa** [comment] 2015-11-07 09:56
@thinkrick I took a first stab at packaging the Emoji One artwork as a font. The result can be seen at (Firefox required) http://miguelsousa.github.io/emojione/
As you probably know, there are [4 different formats for making color fonts](http://blog.symbolset.com/multicolor-fonts). I employed the SVG-in-OpenType solution, mentioned by Paul above, thus the need for Firefox.

If you open the link in another browser, you'll see that the B&W glyphs are just placeholders. Which leads me to the question, is having Emoji One as a font something of interest to you? If so, B&W versions of the SVGs are needed; would you be able to provide them?

**Comment by mikebe11** [comment] 2015-12-22 07:26
Since the addition of a font has happened this issue will be closed. Thanks to those at Adobe who helped make our initial font offering a reality.

**Closed by mikebe11** 2015-12-22 07:26 UTC
Labels: enhancement, help wanted

**Comment by eosrei** [comment] 2016-06-06 19:57
Sorry to bump an old issue, but I thought it relevant to add a link to my EmojiOne SVGinOT font in case anyone finds this issue: https://github.com/eosrei/emojione-color-font
