### ISSUE TITLE
All numbers turns into :one_digit: emoji but its a grandma emoji

### ISSUE THREAD

**Issue by mroftalp** [Ranks/emojione#300] opened 2016-07-10 12:53 UTC
I think there's a bug in the new update

**Comment by caseyahenson** [comment] 2016-07-11 18:06
Can you drop in a screenshot of how and where this is happening?

**Comment by mroftalp** [comment] 2016-07-12 04:30
![screen shot 2016-07-12 at 12 30 05 pm](https://cloud.githubusercontent.com/assets/6789191/16755195/7347cc4e-482c-11e6-87d1-2ee42be10c15.png)
![Uploading Screen Shot 2016-07-12 at 12.30.18 pm.png…]()
![Uploading Screen Shot 2016-07-12 at 12.30.23 pm.png…]()

**Comment by mroftalp** [comment] 2016-07-12 04:31
![screen shot 2016-07-12 at 12 30 05 pm](https://cloud.githubusercontent.com/assets/6789191/16755203/82f196e8-482c-11e6-817d-528a52b4fdbb.png)
![screen shot 2016-07-12 at 12 30 18 pm](https://cloud.githubusercontent.com/assets/6789191/16755204/868886a4-482c-11e6-82eb-4875309196f3.png)
![screen shot 2016-07-12 at 12 30 23 pm](https://cloud.githubusercontent.com/assets/6789191/16755206/8a4b4380-482c-11e6-8089-d2c89a4d5869.png)

**Comment by mroftalp** [comment] 2016-07-12 04:33
Hope you can bring back `emojione.toShort()` to not force all numbers or asterisk (or any char I still haven't discovered) into an :emoji: or put an option to turn it off.

**Comment by roymap** [comment] 2016-07-15 18:21
Any update on this?  We've had to rip out Emojione because of its conversion of all sigle digits to :digit_X: emoji codes.

**Comment by caseyahenson** [comment] 2016-07-15 18:26
This will be fixed with an update scheduled to be released within the next 24 hours.

**Comment by caseyahenson** [comment] 2016-07-16 18:48
This should be fixed in today's 2.2.6 release. Please test and let us know if there are still any issues.

**Closed by caseyahenson** 2016-07-16 18:48 UTC

**Comment by roymap** [comment] 2016-07-18 18:59
Works.  Thanks!

**Comment by mroftalp** [comment] 2016-07-18 22:39
Yes, Thank you!

**Comment by MerlinBB** [comment] 2018-06-26 14:30
Hey there,

I think there might be a regression on this issue (if I've understood correctly).

This demo: https://demos.emojione.com/latest/jstoshort.html is currently converting numbers, asterisks and hashtags.

> Hello * #world 123! 😄
```Hello :asterisk_symbol: :pound_symbol:world :digit_one::digit_two::digit_three:! :smile:```

**Comment by zaidonch** [comment] 2018-07-06 11:48
is there any option not to convert numbers into emojis?
