### ISSUE TITLE
The SVG version of U+264d seems to be broken in v2.2 (and in current git)

### ISSUE THREAD

**Issue by jfkthame** [Ranks/emojione#257] opened 2016-06-04 09:24 UTC
Noticed in the 2.2 release: the outline in 264d.svg is broken and does not render well (in the browsers I've tried, the left "leg" is truncated; in Inkscape it looks even more badly scrambled).

**Comment by caseyahenson** [comment] 2016-06-05 16:52
Thanks for pointing this out! We're looking into it. Are you still seeing the issue with https://github.com/Ranks/emojione/issues/255 as well?

**Comment by Naudiz** [comment] 2016-06-06 15:10
It's even worse than that. The majority of SVGs in 2.2 seem to have massive issues when trying to import them into Inkscape. This has never been an issue in 2.1 or 2.0.

Some like 00a9 are totally messed up beyond any recognition, others like 1f41e or 1f403 are missing important details, but overall it seems there are more broken than working SVGs in the current release.

I really hope this gets fixed. I need to be able to process those SVGs in Inkscape :-/

**Comment by eosrei** [comment] 2016-06-06 17:50
The issue, in [my case](http://xerographer.github.io/reinebow/) and probably here, is caused by the optimized SVG export from Illustrator. It may be fixed in Inkscape 0.92(unreleased): https://bugs.launchpad.net/inkscape/+bug/1284409 A solution for now is to re-export all of the SVG files unoptimized.

I just converted 264d.svg to png using a number of programs on Linux. Nothing renders as depicted in the provided PNG.

Original:
![264d](https://cloud.githubusercontent.com/assets/195061/15831751/f059b53c-2bd3-11e6-98cc-9390aead9285.png)

Inkscape:
![264d-inkscape](https://cloud.githubusercontent.com/assets/195061/15831753/f365d4e0-2bd3-11e6-8028-d5f5e7f0ed96.png)

CarioSVG:
![264d-cairosvg](https://cloud.githubusercontent.com/assets/195061/15831653/7ebaac6a-2bd3-11e6-9e89-472315347a03.png)

Imagemagick/rsvg-convert:
![264d-imagemagick](https://cloud.githubusercontent.com/assets/195061/15831775/0c8de570-2bd4-11e6-9de3-4c899333cdab.png)

PhantomJS/Firefox/Chrome:
![264d-phantomjs-rasterize](https://cloud.githubusercontent.com/assets/195061/15831789/1e10bb6a-2bd4-11e6-83f4-0d96b2da87c7.png)

**Comment by eosrei** [comment] 2016-06-06 19:19
> The majority of SVGs in 2.2 seem to have massive issues when trying to import them into Inkscape.

@Naudiz Confirmed. I'm seeing the same thing here. More than half of the SVGs don't load correctly in Inkscape. Most work fine in PhantomJS/Firefox/Chrome/CarioSVG though, so `264d.svg` seems to have two separate issues. Good example is [1f4a2.svg](https://github.com/Ranks/emojione/blob/8af5fdb690344352e95c2e4a34725a3ceaa0206f/assets/svg/1f4a2.svg) which loads correctly in the browsers, but Inkscape loads as an empty file.

**Comment by caseyahenson** [comment] 2016-06-06 23:24
We'll be releasing 2.2.1 in the next couple of days to repair these issues. This should take care of 264d specifically (which had path issues) and the general re-cleaning of all svgs to ensure proper rendering across the board.

**Comment by eosrei** [comment] 2016-06-06 23:36
Thank you! I'll have the SVGinOT font and Ubuntu PPA updated soon after v2.2.1 is released.

@caseyahenson Don't worry about Imagemagick rendering, librsvg has some long standing bugs. Details: https://strategy.wikimedia.org/wiki/Proposal:Librsvg_development_funding Everything else should work right though.

**Comment by caseyahenson** [comment] 2016-06-09 20:36
2.2.1 Has been released which should should address the SVG issues mentioned here.

**Closed by caseyahenson** 2016-06-09 20:36 UTC
