### ISSUE TITLE
please consider generating web font file and submit it to cdn

### ISSUE THREAD

**Issue by fyears** [Ranks/emojione#201] opened 2016-02-18 05:48 UTC
Suggestion:

Create web font file and submit it to cdn, so that we could use it online like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <style type="text/css">
    @font-face{
        font-family: 'EmojiOne';
        src:  url('https://cdnjs.cloudflare.com/ajax/libs/emojione/2.1.0/assets/fonts/emojione-web.ttf') format('truetype');
    }
    body {
        font-family: 'EmojiOne', sans-serif;
    }
    </style>
  </head>
  <body>
    <h1>Hello, world!</h1>
    <p>😎</p>
  </body>
</html>
```

I've tried the android font file (locally, since cdn doesn't provide it), but it seems that the android font file is not capable in this usage.

**Comment by waldyrious** [comment] 2016-02-18 13:35
:+1:. According to [CDNPerf](https://www.cdnperf.com/) and [this review](http://sixrevisions.com/resources/free-public-cdns/), [CDNJS](https://cdnjs.com/) may be an interesting choice, given that it's geared towards FOSS projects.

**Comment by eosrei** [comment] 2016-02-25 02:12
@fyears The problem is this is a very large set of data. Only Firefox supports the standard (SVG in OpenType) for color fonts. Safari, Chrome, Edge only support their specific proprietary formats right now. So to make a web font, you'd need all of them. It would probably be over 100mb font.

It'll be feasible a few years down the line when everything supports SVGinOT.

**Comment by mikebe11** [comment] 2016-03-08 06:10
@fyears Thanks for the suggestion but we don’t have the means ourselves to produce a webfont. Based on the comment by @eosrei, who has some recent color font experience, this might not even be feasible. If the font really would be as large as he suggests then as a project it just doesn’t seem worth it to us. Maybe someday a black and white webfont will be feasible especially since the size would be much smaller than a full color version.
I’m going to close this issue for now but as things develop if a webfont becomes more of a viable option then we will sincerely consider adding one to our CDN.

**Closed by mikebe11** 2016-03-08 06:10 UTC
